name: payjp_flutter_example
description: Demonstrates how to use the payjp_flutter plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  payjp_flutter:
    path: ../
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.4

flutter:
  uses-material-design: true
