matrix:
  include:
    - language: android
      sudo: false
      jdk: oraclejdk8
      os: linux
      dist: trusty
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      cache:
        directories:
          - $HOME/.pub-cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      android:
        components:
          - tools
          - platform-tools
          - android-28
          - extra-google-m2repository
          - extra-android-m2repository
          - extra-google-google_play_services
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      before_install:
        - cd example
      install:
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter -v build apk

    - language: objective-c
      os: osx
      osx_image: xcode11.3
      cache:
        directories:
          - $HOME/.pub-cache
      before_install:
        - cd example
        - pod setup
        - pod repo update
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter -v build ios --no-codesign