name: payjp_flutter
version: 0.3.3
description: A Flutter plugin for PAY.JP Mobile SDK.
homepage: https://github.com/payjp/payjp-flutter-plugin
repository: https://github.com/payjp/payjp-flutter-plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.0.4
  meta: ^1.3.0

dev_dependencies:
  build_runner:
  built_value_generator: ^8.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: jp.pay.flutter
        pluginClass: PayjpFlutterPlugin
      ios:
        pluginClass: PayjpFlutterPlugin
