name: build-test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  FLUTTER_CHANNEL: stable
  CACHE_NUMBER: 0 # increment to truncate cache
  IOS_SIMULATOR_DEVICE: iPhone 17 Pro
  IOS_SIMULATOR_RUNTIME: iOS-26-0
  USER_JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # setup flutter
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.USER_JAVA_VERSION }}
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
      # configure cache
      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-pub-${{ env.CACHE_NUMBER }}-${{ hashFiles('**/*/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ env.CACHE_NUMBER }}-
            ${{ runner.os }}-pub-
      # check
      - run: make dependencies
      - run: make check

  build-android:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # setup flutter
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.USER_JAVA_VERSION }}
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
      - uses: gradle/actions/setup-gradle@v3
      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-pub-${{ env.CACHE_NUMBER }}-${{ hashFiles('**/*/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ env.CACHE_NUMBER }}-
            ${{ runner.os }}-pub-
      # prepare flutter
      - run: make dependencies
      # build app
      - name: Build android app
        run: make build-android-example
      - name: Run e2e test on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel
          script: make driver-test

  build-ios:
    needs: build
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      # setup flutter
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.USER_JAVA_VERSION }}
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: |
            /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-pub-${{ env.CACHE_NUMBER }}-${{ hashFiles('**/*/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-${{ env.CACHE_NUMBER }}-
            ${{ runner.os }}-pub-
      # prepare flutter
      - run: make dependencies
      # build app
      - name: Build ios app
        run: make build-ios-example
      # connected check
      - name: List all iPhone Simulator
        run: xcrun simctl list devices available
      - name: Start iOS Simulator
        run: |
          UDID=$(xcrun simctl list devices available --json | jq -r '.devices."com.apple.CoreSimulator.SimRuntime.${{ env.IOS_SIMULATOR_RUNTIME }}"[] | select(.name == "${{ env.IOS_SIMULATOR_DEVICE }}").udid')
          xcrun simctl boot "${UDID}"
      - name: Run e2e test
        run: make driver-test

  validate-openapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tool/generator

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: ~/.cache/yarn
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: yarn validate
      run: yarn validate
      env:
        CI: true
